# Generated by Django 4.0.2 on 2022-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='best_friend_name',
            field=models.CharField(max_length=50, verbose_name='best_friend_name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_song',
            field=models.CharField(max_length=50, verbose_name='favorite_song'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_book',
            field=models.CharField(max_length=45, verbose_name='first_book'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mothers_maiden_name',
            field=models.CharField(max_length=60, verbose_name='mothers_maiden_name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='place_of_residence',
            field=models.CharField(max_length=30, verbose_name='place_of_residence'),
        ),
    ]
